In [ ]:
Python: without numpy or sklearn
Q1: Given two matrices please print the product of those two matrices

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]


Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]


Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    return(#multiplication_of_A_and_B)
    
matrix_mul(A, B)

In [3]:
A   = [[1,3,4],
       [2,5,7],
       [5,9,6]]
B   = [[1,0,0],
       [0,1,0],
       [0,0,1]]

row_A= len(A)
col_A= len(A[0])
row_B= len(B)
col_B= len(B[0])

def multiply(A, B):
    if col_A != row_B:
        print('Not Possible')
    else:
        C = [[sum(a*b for a,b in zip(row_A,col_B)) for col_B in zip(*B)] for row_A in A]
        print('A x B is ...')    
        for x in C:
            print(x)
multiply(A, B)


A x B is ...
[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


In [4]:
A   = [[1,2],
       [3,4]]

B   = [[1,2,3,4,5],
       [5,6,7,8,9]]

row_A= len(A)
col_A= len(A[0])
row_B= len(B)
col_B= len(B[0])

def multiply(A, B):
    if col_A != row_B:
        print('Not Possible')
    else:
        C = [[sum(a*b for a,b in zip(row_A,col_B)) for col_B in zip(*B)] for row_A in A]
        print('A x B is ...')
        for x in C:
            print(x)
multiply(A, B)


A x B is ...
[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]


In [5]:
A   = [[1,2],
       [3,4]]

B   = [[1,4],
       [5,6],
       [7,8],
       [9,6]]
C   = []
row_A= len(A)
col_A= len(A[0])
row_B= len(B)
col_B= len(B[0])

def multiply(A, B):
    if col_A != row_B:
        print('Not Possible')
    else: 
        C = [[sum(a*b for a,b in zip(row_A,col_B)) for col_B in zip(*B)] for row_A in A]
        print('A x B is ...')    
        for x in C:
            print(x)
multiply(A, B)


Not Possible


In [ ]:
Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements
consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude. 
assume we are doing the same experiment for 100 times with replacement, 
in each experiment you will print a number that is selected randomly from A.

Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)

In [26]:
import random

d = [0,5,27,6,13,28,100,45,10,79]

def pick_a_number_from_list(d):
    sm = 0   #find sum of numbers in d
    for i in (d):
        sm += i

    d1 = []    #normalised values
    for j in range(len(d)):
        d1.append(d[j]/sm)

     
    d2 = []  # cumulative sum 
    for k in range(len(d1)):
        d2.append(sum(d1[:k+1]))
     


    r = random.uniform(0.0, 1.0)
    print(r)

    number = 0
    for m in range(len(d2)):
        if r >= d2[m] and r <d2[m+1] :
            number = d[m+1]
    return number



    
def sampling_based_on_magnitued():
    d = [0,5,27,6,13,28,100,45,10,79]
    d.sort()
    result = dict()
    print(d, sum(d))
    for n in range(1, 100):
        number = pick_a_number_from_list(d)
        print(number)
        if number not in result:
            result[number] = 1
        else:
            result[number]+=1
            
    print(result)

sampling_based_on_magnitued()

[0, 5, 6, 10, 13, 27, 28, 45, 79, 100] 313
0.6923623192621305
100
0.7749911450109636
100
0.6585486929479516
79
0.789467591273005
100
0.6583136992858056
79
0.21363327901699403
28
0.20608933187641643
28
0.540424999425331
79
0.06720911594563961
13
0.9214052547230865
100
0.987627858353408
100
0.07705487202330497
13
0.9495235810202474
100
0.5927976520492342
79
0.5865213982607762
79
0.8727411291753466
100
0.5788165990487643
79
0.6775988296813669
79
0.3781881338546098
45
0.15808743713817042
27
0.06919244555100579
13
0.0891351937409014
13
0.6984730904009041
100
0.7720060033511299
100
0.9588061635084997
100
0.3079732114190227
45
0.4978902799264404
79
0.26767983393772266
28
0.7688835042463106
100
0.10046888740940707
13
0.5330441155142198
79
0.7607813912239296
100
0.03629506022321227
10
0.9041723724907363
100
0.9254942259564604
100
0.8141059339756705
100
0.1071143757417079
13
0.6231677483147278
79
0.8739634569947522
100
0.38302697104453975
45
0.543612089104995
79
0.41526921058569033
45
0.38010875

In [ ]:
Q3: Replace the digits in the string with #
consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #

Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####

In [8]:
import re
#A = '234'
#A = 'a2b3c4d5e7f9'
#A = 'abc'
A = '#2a$#b%c%561#'

pattern = re.compile(r'\d')
String = pattern.findall(A)
for match in String:
    if match == int:
        print('')
    else:
        print('#', end='')
        


####

In [9]:
import re
#A = '234'
A = 'a2b3c4d5e7f9'
#A = 'abc'
#A = '#2a$#b%c%561#'

pattern = re.compile(r'\d')
String = pattern.findall(A)

def replace_digits(String):
    for match in String:
        if match == int:
            print('')
        else:
            print('#', end='')
replace_digits(String)

######

In [ ]:
Q4: Students marks dashboard
consider the marks list of class students given two lists
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80]
from the above two lists the Student[0] got Marks[0], Student[1] got Marks[1] and so on

your task is to print the name of students a. Who got top 5 ranks, in the descending order of marks
b. Who got least 5 ranks, in the increasing order of marks
d. Who got marks between >25th percentile <75th percentile, in the increasing order of marks

Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    top_5_students = # compute this
    # write code for computing top least 5 students
    least_5_students = # compute this
    # write code for computing top least 5 students
    students_within_25_and_75 = # compute this
    
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(# those values)

In [17]:
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

dash_board = dict(zip(Students, Marks))
print('dash_board = ')
print(dash_board)

a_max = {key: dash_board[key] for key in sorted(dash_board, key=dash_board.get, reverse=True)[:5]}
print('top_5_students = ')
print(a_max)

b_min = {key: dash_board[key] for key in sorted(dash_board, key=dash_board.get)[:5]}
print('least_5_students = ')
print(b_min)


def Q1(Marks):
    return sorted(Marks)[int(len(Marks) * .25)]

print('25% Quartile is ')
print(Q1(Marks))

def Q3(Marks):
    return sorted(Marks)[int(len(Marks) * .75)]

print('75% Quartile is ')
print(Q3(Marks))

IQR = []
for i in Marks:
    if i>=35 and i<78:
        IQR.append(i)
print('IQR is ')
print(IQR)

dash_board = {'student1': 45, 'student2': 78, 'student3': 12, 'student4': 14, 'student5': 48, 'student6': 43, 'student7': 47, 'student8': 98, 'student9': 35, 'student10': 80}
reversed_dictionary = {value : key for (key, value) in dash_board.items()}
IQR = [45, 48, 43, 47, 35]
IQR.sort()

for k in IQR:
    if k in reversed_dictionary:
        print(k, reversed_dictionary[k])

dash_board = 
{'student1': 45, 'student2': 78, 'student3': 12, 'student4': 14, 'student5': 48, 'student6': 43, 'student7': 47, 'student8': 98, 'student9': 35, 'student10': 80}
top_5_students = 
{'student8': 98, 'student10': 80, 'student2': 78, 'student5': 48, 'student7': 47}
least_5_students = 
{'student3': 12, 'student4': 14, 'student9': 35, 'student6': 43, 'student1': 45}
25% Quartile is 
35
75% Quartile is 
78
IQR is 
[45, 48, 43, 47, 35]
35 student9
43 student6
45 student1
47 student7
48 student5


In [ ]:
Q5: Find the closest points
consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)]
and a point P=(p,q)
your task is to find 5 closest points(based on cosine distance) in S from P
cosine distance between two points (x,y) and (p,q) is defind as  cos−1((x⋅p+y⋅q)(√x2+y2)⋅(√p2+q2)) 

Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print() #print the returned values

In [16]:
import math
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

def closest_points_to_p(S, P):
    
    S.sort(key = lambda x: math.acos(((x[0]*(3))+(x[1]*(-4)))/((math.sqrt((x[0]**2)+(x[1]**2))) *(math.sqrt(((3)**2)+
                                                                                                            ((-4)**2))))))
    print(S[:5])

    return closest_points_to_p


points = closest_points_to_p(S, P)


[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


In [ ]:
Q6: Find Which line separates oranges and apples
consider you have given two set of data points in the form of list of tuples like
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
and set of line equations(in the string formate, i.e list of strings)
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
your task is to for each line that is given print "YES"/"NO", you will print yes, 
if all the red points are one side of the line and blue points are other side of the line, otherwise no
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

Output:
YES
NO
NO
YES

In [ ]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print() # the returned value

In [19]:
import re
import math
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

red_plot = []
blu_plot = []
red_chck = []
blu_chck = []

for line in Lines:
    a, b, c = [float(x.strip()) for x in re.split('x|y', line)]
    
    R = []
    B = []
    for h in range(len(Red)):
        rd = ((a*Red[h][0]) + (b*Red[h][1]) + c)
        R.append(rd)
    red_plot.append(R)
    for i in range(len(Blue)):
        bu = ((a*Blue[i][0]) + (b*Blue[i][1]) + c)
        B.append(bu)
    blu_plot.append(B)
    
red_chck = [all(j > 0 for j in m) for m in red_plot]
blu_chck = [all(k < 0 for k in n) for n in blu_plot]


for p in range(len(red_chck)):
    if red_chck[p]==True and blu_chck[p]==True:
        print('Yes')
    else:
        print('No')

Yes
No
No
Yes


In [ ]:
Q7: Filling the missing values in the specified formate
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places 

Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) 
    is distributed qually to all 5 places

Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 
    is distributed qually to all 5 missing values that are right to it

Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _" 
    you need fill the missing values
Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex:

Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    return #list of values

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(# print above values)

In [20]:
#S1 = "_,_,_,24"
#Output1: 6,6,6,6

#S2 = "40,_,_,_,60"
#Output2: 20,20,20,20,20

#S3 = "80,_,_,_,_"
#Output3: 16,16,16,16,16

S4 = "_,_,30,_,_,_,50,_,_"
#Output4: 10,10,12,12,12,12,4,4,4



def curve_smoothing(S4):
    SS4 = S4.split(',')
    blanks = 0
    first_num = 0
    for i in range(len(SS4)):
        if SS4[i] == '_':
            blanks+=1
        else:
            for j in range(i+1):
                SS4[j] = str((float(SS4[i]) / (blanks + 1)))
            first_num = i
            first_set_values = float(SS4[i])
            break
    
    
    
    
    mid_blanks = 0
    second_num = 0
    for k in range(first_num + 1, len(SS4)):
        if SS4[k] != '_':
            mid_blanks = ((k + 1) - first_num)
            second_num = k
            break
            
    second_num_value = float(SS4[second_num])
    for m in range(first_num, second_num+1):
        SS4[m] = str((second_num_value + first_set_values) / mid_blanks)
        
    last_set = float(SS4[second_num])
    for n in range(second_num, len(SS4)):
        SS4[n] = str(last_set / (len(SS4) - second_num))
        
    
        
    return SS4
            
S4 = "_,_,30,_,_,_,50,_,_"

print(curve_smoothing(S4))

['10.0', '10.0', '12.0', '12.0', '12.0', '12.0', '4.0', '4.0', '4.0']


In [ ]:
Q8: Filling the missing values in the specified formate
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]] 
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5) 
2. the second column S will contain only 3 uniques values (S1, S2, S3)
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
Ex:
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3

In [21]:
from fractions import Fraction
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
F_ele = [ele[0] for ele in A]
S_ele = [ele[1] for ele in A]

def values(F, S):
    count_F = 0
    count_S = 0
    
    for i in range(len(A)):
        if A[i][1] == S:
            count_S += 1
            if A[i][0] == F:
                count_F += 1
    print('P(F={}|S=={})='.format(F,S), Fraction(count_F,count_S))

for m in F_ele:
    for n in S_ele:
        values(m,n)


    




P(F=F1|S==S1)= 1/4
P(F=F1|S==S2)= 1/3
P(F=F1|S==S3)= 0
P(F=F1|S==S2)= 1/3
P(F=F1|S==S3)= 0
P(F=F1|S==S2)= 1/3
P(F=F1|S==S1)= 1/4
P(F=F1|S==S1)= 1/4
P(F=F1|S==S3)= 0
P(F=F1|S==S1)= 1/4
P(F=F2|S==S1)= 1/4
P(F=F2|S==S2)= 1/3
P(F=F2|S==S3)= 1/3
P(F=F2|S==S2)= 1/3
P(F=F2|S==S3)= 1/3
P(F=F2|S==S2)= 1/3
P(F=F2|S==S1)= 1/4
P(F=F2|S==S1)= 1/4
P(F=F2|S==S3)= 1/3
P(F=F2|S==S1)= 1/4
P(F=F3|S==S1)= 0
P(F=F3|S==S2)= 1/3
P(F=F3|S==S3)= 1/3
P(F=F3|S==S2)= 1/3
P(F=F3|S==S3)= 1/3
P(F=F3|S==S2)= 1/3
P(F=F3|S==S1)= 0
P(F=F3|S==S1)= 0
P(F=F3|S==S3)= 1/3
P(F=F3|S==S1)= 0
P(F=F1|S==S1)= 1/4
P(F=F1|S==S2)= 1/3
P(F=F1|S==S3)= 0
P(F=F1|S==S2)= 1/3
P(F=F1|S==S3)= 0
P(F=F1|S==S2)= 1/3
P(F=F1|S==S1)= 1/4
P(F=F1|S==S1)= 1/4
P(F=F1|S==S3)= 0
P(F=F1|S==S1)= 1/4
P(F=F2|S==S1)= 1/4
P(F=F2|S==S2)= 1/3
P(F=F2|S==S3)= 1/3
P(F=F2|S==S2)= 1/3
P(F=F2|S==S3)= 1/3
P(F=F2|S==S2)= 1/3
P(F=F2|S==S1)= 1/4
P(F=F2|S==S1)= 1/4
P(F=F2|S==S3)= 1/3
P(F=F2|S==S1)= 1/4
P(F=F3|S==S1)= 0
P(F=F3|S==S2)= 1/3
P(F=F3|S==S3)= 1/3
P(F=F3|S==S2)= 

In [22]:
Q9: Given two sentances S1, S2
You will be given two sentances S1, S2 your task is to find
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
Ex:

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']

SyntaxError: invalid syntax (<ipython-input-22-7fbd2fe06556>, line 1)

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(#the above values)

In [23]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

SS1 = S1.split()
SS2 = S2.split()
a = len(set(SS1).intersection(set(SS2)))
print(a)
b = list(set(SS1) - set(SS2))
print(b)
c = b = list(set(SS2) - set(SS1))
print(c)


7
['5', 'F', 'first']
['S', 'second', '3']


In [ ]:
Question 10:

In [27]:

import math
#f(Y,Yscore)=−1∗1/nΣforeachY,Yscorepair(Ylog10(Yscore)+(1−Y)log10(1−Yscore))
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

def compute_log_loss(A):
    sum = 0
    for i in range(len(A)):    #ΣforeachY,Yscorepair  #(Ylog10(Yscore)+(1−Y)log10(1−Yscore))
        sum = sum + ((A[i][0] * math.log(A[i][1],10)) + ((1-A[i][0]) * (math.log(1-A[i][1],10))))
    return sum

print((compute_log_loss(A)*(1/8)*(-1)))


0.42430993457031635


In [ ]:
Q10: Given two sentances S1, S2
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]] 
consider its like a martrix of n rows and two columns
a. the first column Y will contain interger values
b. the second column  Yscore  will be having float values